---
- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes
    when: ansible_distribution == 'ubuntu'  # check if the target system is ubuntu...

  - name: install apache2 package and php
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == 'ubuntu'  # install apache2  only on ubuntu-based systems...  

   

  - name: update repo index
    dnf:
      update_cache: yes
    when: ansible_distribution == 'centos'  # check if the target system is centos...

  - name: install apache2 package and php for centos
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == 'centos'  # install apache2  only on centos-based systems...  

